from __future__ import annotations

from typing import Protocol

from nocturnix.models import (
    ApprovalRecord,
    AuditEvent,
    ChatMessageRecord,
    ConversationRecord,
    RepairIntakeRecord,
    UserPreferences,
)


class ApprovalRepository(Protocol):
    def add(self, approval: ApprovalRecord) -> ApprovalRecord: ...
    def get(self, approval_id: str) -> ApprovalRecord | None: ...
    def update(self, approval: ApprovalRecord) -> ApprovalRecord: ...
    def list_for_user(
        self, user_id: str, offset: int = 0, limit: int = 100
    ) -> list[ApprovalRecord]: ...
    def claim_execution(self, approval_id: str, owner_user_id: str) -> ApprovalRecord | None: ...


class AuditRepository(Protocol):
    def add(self, event: AuditEvent) -> AuditEvent: ...
    def list_for_user(
        self, user_id: str, category: str | None, offset: int, limit: int
    ) -> list[AuditEvent]: ...
    def count_candidates(self, before_iso: str) -> int: ...


class ConversationRepository(Protocol):
    def get(self, conversation_id: str) -> ConversationRecord | None: ...
    def add(self, conversation: ConversationRecord) -> ConversationRecord: ...
    def update(self, conversation: ConversationRecord) -> ConversationRecord: ...
    def list_for_user(self, user_id: str, offset: int, limit: int) -> list[ConversationRecord]: ...


class MessageRepository(Protocol):
    def add(self, message: ChatMessageRecord) -> ChatMessageRecord: ...
    def list_for_conversation(self, conversation_id: str) -> list[ChatMessageRecord]: ...


class RepairIntakeRepository(Protocol):
    def add(self, intake: RepairIntakeRecord) -> RepairIntakeRecord: ...
    def get(self, intake_id: str) -> RepairIntakeRecord | None: ...
    def list_for_user(self, user_id: str, offset: int, limit: int) -> list[RepairIntakeRecord]: ...


class PreferenceRepository(Protocol):
    def get(self, user_id: str) -> UserPreferences | None: ...
    def upsert(self, preferences: UserPreferences) -> UserPreferences: ...


class MockMetadataRepository(Protocol):
    def upsert_email(self, user_id: str, message_id: str, metadata: dict[str, object]) -> None: ...
    def upsert_calendar(self, user_id: str, event_id: str, metadata: dict[str, object]) -> None: ...
